// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhS4apo5eJzx6uWe_HFc0vxorugBojNeo',
    appId: '1:201453646516:web:fe4450465d9eb911df9de1',
    messagingSenderId: '201453646516',
    projectId: 'chaty-app-f54cf',
    authDomain: 'chaty-app-f54cf.firebaseapp.com',
    storageBucket: 'chaty-app-f54cf.appspot.com',
    measurementId: 'G-XQXXVL8NHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_TboG5bdqi3W9g_2CmuzoUXkPFnsql94',
    appId: '1:201453646516:android:4615fbf71d413bdddf9de1',
    messagingSenderId: '201453646516',
    projectId: 'chaty-app-f54cf',
    storageBucket: 'chaty-app-f54cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1doMquouNB-ZkZlq7NwyIqWxTs8NQmUk',
    appId: '1:201453646516:ios:cc235a81d43537acdf9de1',
    messagingSenderId: '201453646516',
    projectId: 'chaty-app-f54cf',
    storageBucket: 'chaty-app-f54cf.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1doMquouNB-ZkZlq7NwyIqWxTs8NQmUk',
    appId: '1:201453646516:ios:cc235a81d43537acdf9de1',
    messagingSenderId: '201453646516',
    projectId: 'chaty-app-f54cf',
    storageBucket: 'chaty-app-f54cf.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhS4apo5eJzx6uWe_HFc0vxorugBojNeo',
    appId: '1:201453646516:web:d5410189ad794b7bdf9de1',
    messagingSenderId: '201453646516',
    projectId: 'chaty-app-f54cf',
    authDomain: 'chaty-app-f54cf.firebaseapp.com',
    storageBucket: 'chaty-app-f54cf.appspot.com',
    measurementId: 'G-HC9G57YK9K',
  );
}
